#+TITLE: Appendix-A-Building-And-Developing-With-Leiningen
#+DATE: 2025-12-08 Mon
#+AUTHOR: Agung Tuanany
#+DESCRIPTION: Clojure, book, A summary per chapter from book clojure-for-the-brave-and-true.
#+KEYWORDS: programming, clojure, clojure-for-the-brave-and-true.
#+OPTIONS: toc:nil num:nil

Writing software in any language involves generating /artifacts/, which are
executable files or library packages that are meant to be deployed or shared. It
also involves managing dependent artifacts, also called /dependencies/, by
ensuring that they're loaded into the project you're building. The most popular
tools among Clojurists for managing artifacts is Leiningen, and this appendix
will show you how to use it. You'll also learn how to use Leiningen to totally
enhancify your development experience with /plug-ins/.

* The Artifact Ecosystem

Because Clojure is hosted on the Java Virtual Machine (JVM), Clojure artifacts
are distributed as JAR files (covered in Chapter 12). Java land already has an
entire artifact ecosystem for handling JAR files, and Clojure use it. /Artifact
ecosystem/ isn't an official programming term; I use it to refer the suite of
tools, resources, and conventions used to identify distribute artifacts. Java's
ecosystem grew up around the Maven build tool, and because Clojure use this
ecosystem, you'll often see references to Maven. Maven is huge tool that can
perform all kinds of wacky project management tasks. Thankfull, you don't need
to get your PhD in Mavenology to be an Effective Clojurist. The only feature you
need to know is that Maven specifies a pattern for identifying artifacts that
Clojure projects adhere to, and its also specifies how to host these artifacts
in Maven /repositories/, which are just servers that store artifact for
distribution.

** Identification

Maven artifacts need a /group ID/, and /artifact ID/, and a /version/. You can
specify these for your project in the /project.clj/ file. Here's what the first
time of /[[file:~/Documents/clojure-for-the-brave-and-true/Part-I-environment-setup/examples/clojure-noob/project.clj][project.clj]]/ looks like for the /clojure-noob/ project that you created
in Chapter 1:

#+begin_src clojure :results value verbatim :exports both eval: never-export
(defproject clojure-noob "0.1.0-SNAPSHOT")
#+end_src

/clojure-noob/ is both the group ID and the artifacts ID of your project, and
"0.1.0-SNAPSHOT" is its version. In general, versions are permanent; if you
deploy an artifact with version, 0.1.0 to a repository, you can't make changes
to the artifact and deploy it using the same version number. You'll need to
change the version number. (Many programmers like the Semantic Versioning
system, which you can read about at http://semver.org). If you want to indicate
that the version is work in progress and you plan to keep updating it, you can
append /-SNAPSHOT/ to your version number.

If you want your group ID to be different from your artifact ID, you can
separate the two with a slash like so:

#+begin_src clojure :results value verbatim :exports both eval: never-export
  (defproject group-id/artifact-id "0.1.0-SNAPSHOT")
#+end_src

Often, developers will use their company name or their GitHub username as the
group ID.

** Dependencies

Your /project.clj/ file also includes a line that looks like this, which lists
your project's dependencies:

#+begin_src clojure :results value verbatim :exports both eval: never-export
  :dependencies [[org.clojure/clojure "1.11.1"]]
#+end_src

If you want to use a library, add it this dependency vector using the same
naming schema that you use to name your project. For example, if you want to
easily work with dates and times, you could add the clj-time library, like this:

#+begin_src clojure :results value verbatim :exports both eval: never-export
    :dependencies [[org.clojure/clojure 1.11.1]
                   [clj-time "0.15.2"]]
#+end_src

The next time you start your project, either by running it or by starting a
REPL, Leiningen will automatically download clj-time and make it available
within your project.

The Clojure community has created a multitude of useful libraries, and a good
place to look for them is the Clojure Toolbox at
https://www.clojure-toolbox.com/, which categorizes according to their purpose.
Nearly every Clojure library provides its identifier at the top of its README,
making it easy for you to figure out how to add it to your Leiningen
dependencies.

Sometimes you might want to use a Java library, but the identifier isn't as
readily available. If you want to add Apache Commons Email, for example you have
to search online until you find a web page that contains something like this:

#+begin_src xml :results value verbatim :exports both eval: never-export
  <dependency>
    <groupId>org.apace.commons</groupId>
    <artifactId>comons-email</artifactId>
    <version>1.3.3</version>
  </dependency>
#+end_src

This XML is how Java projects communicate their Maven identifier. To add it your
Clojure project, you'd change your /:dependencies/ vector so it looks like this:

#+begin_src clojure :results value verbatim :exports both eval: never-export
  :dependencies [[org.clojure/clojure "1.11.1"]
                 [clj-time "0.15.2"]
                 [org.apache.commons/commons-email "1.3.3"]]
#+end_src

The main Clojure repository is Clojars (https:/clojars.org) and the main Java
repository is the Central Repository (https://search.maven.org) or
(https://search.maven.org/?eh=) which is often referred to as just /Central/ in
the same way that San Francisco resident refer to San Francisco as /the city/.
You can use these sites to find libraries and their identifiers.

To deploy your own projects to Clojars, all you have yo do is create an account
there and run /lein deploy clojars/ in your projects. This task generates
everything necessary for a Maven artifact to be stored in a repository,
including a POM file (which I won't go into) and a JAR file. Then it uploads
them to Clojars.

** Plug-Ins

Leiningen lets you use /plug-ins/, which are libraries that help you when you're
writing code. For example, the Eastwood plug-in is a Clojure lint tool; it
identifies poorly written code. You'll usually want to specify your plug-ins in
the file /$HOME/.lein/profiles.clj/ to add Eastwood, you'd change /profiles.clj/
to look like this:

#+begin_src clojure :results value verbatim :exports both eval: never-export
  {:user {:plugins [[jonase/eastwood "0.2.1"]] }}
#+end_src

This enables an /eastwood/ Leiningen task for all your projects, which you can
run with /lein eastwood/ at the project's root.

[[https://codeberg.org/leiningen/leiningen/][Leiningen's GitHub]] project page has excellent documentation on how to use
profiles and plug-ins.

* Summary

This appendix focused on the aspect of project management that are important but
that are difficult to find out about, like what Maven is and Clojure's
relationship to it. It showed you how to use Leiningen to name your project,
specify dependencies, and deploy to Clojars. Leiningen offers a lot of
functionality for software development tasks thatdon't involve actually writing
your code. If you want to find out more, check out the Leiningen tutorial online
at https://github.com/technomancy/leiningen/blob/stable/doc/TUTORIAL.md/.
